### ISSUE TITLE
Not working in iOS 9.2.1

### ISSUE THREAD

**Issue by xereda** [gbenvenuti/cordova-plugin-screen-orientation#86]
The plugin is not working on ios 9.2.1. It crashes the app, accusing the following error in xcode:

/ **
  * Registers obervers after plugin was initialized.
  * /
void swizzled_pluginInitialize (id self, SEL _cmd)
{

The xcode shows this message: "Thread 1: EXC_BAD_ACCESS (code = 2, address = 0x39aff8)"

I followed the steps in this tutorial: http://www.gajotres.net/changing-locking-screen-orientation-in-ionic-application/2/

Tks for return

Jackson

**Comment by xereda** [comment]
Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.7.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.2 Build version 7C68

**Comment by govarthananve** [comment]
After update cordova platform ios i got error like this

In file included from /MApps/appname/platforms/ios/M-Tutor/Plugins/cordova-plugin-screen-orientation/YoikScreenOrientation.m:24:
/MApps/M-Tutor/platforms/ios/appname/Plugins/cordova-plugin-screen-orientation/YoikScreenOrientation.h:26:9: fatal error: 
      'Cordova/CDVShared.h' file not found
#import <Cordova/CDVShared.h>
        ^
1 error generated.

** BUILD FAILED **

**Comment by gbenvenuti** [comment]
Hi @xereda  and @govarthananve see my comment in #84 on this, the plugin does not work on ios9

**Comment by govarthananve** [comment]
@gbenvenuti Thank you replay

**Comment by dinhtuan1991vt** [comment]
Please fix this bug

**Comment by AbraXus** [comment]
+1 here. Any news on this?

**Comment by midorikocak** [comment]
https://github.com/gbenvenuti/cordova-plugin-screen-orientation/pull/97

**Comment by tony--** [comment]
@xereda - @gbenvenuti has released 1.4.2 which should fix this issue. Will you try 1.4.2 and provide an update, please?

**Comment by rbarriuso** [comment]
v1.4.2 works on iPhone 5s with iOS 9.3.2

**Comment by tony--** [comment]
@rbarriuso - thanks for the confirmation, I'll close this as resolved.
OP or other commenters - please provide additional feedback if this issue is not resolved for you.
